### ISSUE TITLE
weights for sku10k

### ISSUE THREAD

**Issue by legnaro** [smackiaa/Yolov5-SKU110K#1]
Hello, congrats for this amazing project!

I trying to train the databse sku110k but still with no luck! Is there a chance to post the weights for trained database to sku-110k ?

tks

**Comment by suryanshgupta9933** [comment]
Thanks @legnaro ,
The weights are provided in the repo under `weights` directory. Use git lfs to install the weights.
# Installation
```
git lfs install
git clone https://github.com/suryanshgupta9933/Dense-Object-Detection.git
```

This will download the repo for you including the weights of yolo.

**Comment by legnaro** [comment]
tks a lot ! :-)
